const baseUrl = "http://localhost:3001/api/document";

const base = {
  nome_interno_solicitacao: "REQ-001",
  tecnologia_proposta: "Starlink",
  tipo_solucao_desejada: "internet principal",
  urgencia: "normal",
  data_desejada_implantacao: "2026-06-01",
  origem_demanda: "Inbound",
  comercial_responsavel: "Comercial A",
  segmento_cliente: "Varejo",
  porte_cliente: "medio",
  quantidade_sites_escopo: "1",
  demanda_site_unico_multi_site: "site unico",
  padronizacao_sites: "sim",
  proposta_unica_ou_por_site: "unica",
  necessita_visita_antes_proposta: "nao",
  prazo_contratual_imposto_cliente: "nao",
  necessita_modelo_tese_cliente: "nao",
  nome_prospect_cliente: "Cliente X",
  segmento_atuacao: "Varejo",
  nome_contato_comercial: "Contato C",
  telefone_contato_comercial: "11999999999",
  email_contato_comercial: "c@x.com",
  nome_contato_tecnico: "Contato T",
  telefone_contato_tecnico: "11988888888",
  email_contato_tecnico: "t@x.com",
  existe_ti_interna: "sim",
  existe_terceiro_ti: "nao",
  nome_site: "Matriz",
  endereco_completo: "Rua A, 10",
  cep: "01000-000",
  cidade: "SP",
  estado: "SP",
  pais: "Brasil",
  tipo_local: "escritorio",
  ambiente: "urbano",
  mais_de_um_ponto_mesmo_site: "nao",
  agendamento_previo: "nao",
  restricao_documentacao_acesso: "nao",
  restricao_seguranca_patrimonial: "nao",
  restricao_trabalho_altura: "nao",
  escolta_obrigatoria: "nao",
  autorizacao_proprietario: "sim",
  risco_vandalismo: "nao",
  risco_ambiental: "nao",
  objetivo_principal_link: "Conectividade",
  link_principal_ou_complementar: "principal",
  link_backup: "nao",
  link_contingencia_critica: "nao",
  link_temporario: "nao",
  link_substituira_atual: "sim",
  link_ampliara_rede: "nao",
  quer_reduzir_indisponibilidade: "sim",
  quer_aumentar_performance: "sim",
  quer_reduzir_custo: "nao",
  conectividade_sem_alternativa: "nao",
  quer_mobilidade: "nao",
  ja_usa_satelite: "nao",
  problemas_atuais_motivam: "lentidao",
  impacto_dor: "operacional",
  data_critica_funcionando: "nao",
  contrato_penalidade_atraso_cliente: "nao",
  qtd_total_usuarios: "50",
  qtd_usuarios_simultaneos: "30",
  qtd_dispositivos_simultaneos: "45",
  perfil_medio_usuario: "moderado",
  qtd_estacoes_fixas: "25",
  qtd_dispositivos_moveis: "20",
  uso_visitantes: "nao",
  uso_terceiros: "nao",
  turnos_mesma_infra: "nao",
  iot_dependentes_link: "nao",
  cameras_ip_dependentes_link: "nao",
  telefones_ip_dependentes_link: "nao",
  expectativa_aumento_usuarios: "nao",
  novos_sites_ou_expansao: "nao",
  existe_internet_atualmente: "sim",
  conexao_atual_atende: "nao",
  link_secundario_existente: "nao",
  failover_atual: "nao",
  balanceamento_atual: "nao",
  sdwan_atual: "nao",
  deseja_manter_link_atual: "nao",
  deseja_substituir_link_atual: "sim",
  deseja_solucao_hibrida: "nao",
  escopo_inclui_wifi: "nao",
  deseja_cobertura_wifi: "nao",
  paredes_obstrucoes_criticas: "nao",
  necessidade_roaming: "nao",
  necessidade_ssids_separados: "nao",
  necessidade_portal_guest: "nao",
  necessidade_autenticacao_corporativa: "nao",
  exigencia_gestao_wifi: "nao",
  exigencia_mapa_calor_survey: "nao",
  exigencia_cobertura_externa: "nao",
  cliente_usa_vpn: "nao",
  vpn_critica_operacao: "nao",
  local_previsto_antena: "telhado",
  tensao_disponivel: "220V",
  horario_suporte_desejado: "horario comercial",
  tempo_resposta_desejado: "8h",
  tempo_solucao_desejado: "24h",
  local_remoto: "nao",
  modelo_oferta: "venda",
  complexidade_tecnica: "media",
  nivel_risco_tecnico: "medio",
  nivel_risco_logistico: "medio",
  nivel_risco_comercial: "medio",
  necessidade_visita_tecnica: "nao",
  premissas_tecnicas_obrigatorias: "premissas",
  exclusoes_tecnicas_obrigatorias: "exclusoes",
  restricoes_identificadas: "nenhuma",
  solucao_recomendada: "starlink",
  itens_tecnicos_obrigatorios: "itens",
  itens_tecnicos_recomendados: "itens",
  itens_opcionais: "itens",
  servicos_tecnicos_obrigatorios: "servicos",
  servicos_tecnicos_recomendados: "servicos",
  obs_para_comercial: "ok",
  aprovacao_tecnica: "aprovada",
  justificativa_decisao: "ok",
};

const scenarios = [
  {
    id: "R1-urgencia-justificativa",
    data: { ...base, urgencia: "urgente", justificativa_urgencia: "" },
    expectStatus: 400,
  },
  {
    id: "R2-voip-qos",
    data: { ...base, voip: "sim", ha_necessidade_de_qos: "nao" },
    expectStatus: 400,
  },
  {
    id: "R3-vpn-completo",
    data: { ...base, cliente_usa_vpn: "sim", tipo_vpn: "" },
    expectStatus: 400,
  },
  {
    id: "R4-nat-cgnat-bloqueio",
    data: {
      ...base,
      cliente_usa_vpn: "sim",
      tipo_vpn: "IPsec",
      vpn_eventual_ou_continua: "continuo",
      sistemas_dependem_vpn: "ERP",
      ha_necessidade_de_tunel_permanente: "sim",
      ha_necessidade_de_multiplos_tuneis: "nao",
      ha_necessidade_de_redundancia_de_vpn: "nao",
      ha_dependencia_de_ip_publico: "sim",
      ha_dependencia_de_ip_fixo: "sim",
      ha_dependencia_de_whitelist: "sim",
      ha_restricao_de_nat_cgnat: "sim",
      ha_portas_protocolos_especificos_exigidos: "sim",
      ha_exigencia_de_equipamento_especifico_para_vpn: "nao",
      ha_historico_de_problema_atual_com_vpn: "nao",
      ha_equipe_do_cliente_que_validara_a_vpn: "sim",
      ha_necessidade_de_teste_de_homologacao: "sim",
    },
    expectStatus: 400,
  },
  {
    id: "R5-multisite-obrigatorio",
    data: { ...base, quantidade_sites_escopo: "2", ms_qtd_total_sites: "" },
    expectStatus: 400,
  },
  {
    id: "R6-locacao-recorrencia",
    data: { ...base, modelo_oferta: "locacao", ha_mensalidade_recorrente: "nao" },
    expectStatus: 400,
  },
  {
    id: "R7-terceiro-ti-contato",
    data: { ...base, existe_terceiro_ti: "sim", contato_tecnico_externo: "" },
    expectStatus: 400,
  },
  {
    id: "R8-cenario-valido-gera-documento",
    data: { ...base, ha_mensalidade_recorrente: "sim", ha_budget_estimado: "sim", voip: "nao" },
    expectStatus: 200,
  },
];

for (const scenario of scenarios) {
  const response = await fetch(baseUrl, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-api-key": process.env.FORMSIS_API_KEY ?? "trocar-por-chave-forte",
      "x-user-email": "qa@formsis.local",
      "x-user-role": "PRE_VENDAS",
    },
    body: JSON.stringify({ data: scenario.data }),
  });
  const ok = response.status === scenario.expectStatus;
  let details = "";
  if (!ok) {
    try {
      const payload = await response.json();
      details = ` details=${JSON.stringify(payload)}`;
    } catch {
      details = "";
    }
  }
  console.log(`${ok ? "PASS" : "FAIL"} ${scenario.id} status=${response.status} expected=${scenario.expectStatus}${details}`);
}
